root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"
bin = "./tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_regex = ["_test.go"]
include_ext = ["go", "toml", "env"]
kill_delay = "0s"
stop_on_error = true

[log]
time = false

[misc]
clean_on_exit = true
