package handler

import (
	"context"
	"encoding/json"
	"time"

	"github.com/Rengoku1926/wp_proto/apps/backend/internal/logger"
	"github.com/Rengoku1926/wp_proto/apps/backend/internal/model"
	"github.com/Rengoku1926/wp_proto/apps/backend/internal/repository"
	"github.com/google/uuid"
	"github.com/gorilla/websocket"
)

const (
	writeWait       = 10 * time.Second
	pongWait        = 60 * time.Second
	pingPeriod      = (pongWait * 9) / 10
	maxMessageSize  = 512 * 1024
	sendChannelSize = 256
)

type Envelope struct {
	Type    string          `json:"type"`
	Payload json.RawMessage `json:"payload"`
}

type DirectMessage struct {
	ClientID string `json:"client_id"` // idempotency key generated by sender
	To       string `json:"to"`
	Content  string `json:"content"`
}

type Client struct {
	hub     *Hub
	conn    *websocket.Conn
	userID  string
	send    chan []byte
	msgRepo *repository.MessageRepo
}

func NewClient(hub *Hub, conn *websocket.Conn, userID string, msgRepo *repository.MessageRepo) *Client {
	return &Client{
		hub:     hub,
		conn:    conn,
		userID:  userID,
		send:    make(chan []byte, sendChannelSize),
		msgRepo: msgRepo,
	}
}

func (c *Client) readPump() {
	defer func() {
		c.hub.unregister <- c
		c.conn.Close()
		logger.Log.Debug().Str("userID", c.userID).Msg("readPump exited")
	}()

	c.conn.SetReadLimit(maxMessageSize)
	c.conn.SetReadDeadline(time.Now().Add(pongWait))
	c.conn.SetPongHandler(func(string) error {
		c.conn.SetReadDeadline(time.Now().Add(pongWait))
		return nil
	})

	for {
		_, message, err := c.conn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseNormalClosure) {
				logger.Log.Warn().Err(err).Str("userID", c.userID).Msg("unexpected websocket close")
			}
			return
		}

		var env Envelope
		if err := json.Unmarshal(message, &env); err != nil {
			logger.Log.Warn().Err(err).Str("userID", c.userID).Msg("invalid message envelope")
			continue
		}

		switch env.Type {
		case "dm":
			c.handleDirectMessage(env.Payload)
		default:
			logger.Log.Warn().Str("type", env.Type).Str("userID", c.userID).Msg("unknown message type")
		}
	}
}

func (c *Client) handleDirectMessage(payload json.RawMessage) {
	var dm DirectMessage
	if err := json.Unmarshal(payload, &dm); err != nil {
		logger.Log.Warn().Err(err).Str("userID", c.userID).Msg("invalid DM payload")
		return
	}

	senderUUID, err := uuid.Parse(c.userID)
	if err != nil {
		logger.Log.Warn().Err(err).Str("userID", c.userID).Msg("sender userID is not a valid UUID")
		return
	}
	recipientUUID, err := uuid.Parse(dm.To)
	if err != nil {
		logger.Log.Warn().Err(err).Str("to", dm.To).Msg("recipient userID is not a valid UUID")
		return
	}

	clientID, err := uuid.Parse(dm.ClientID)
	if err != nil {
		// If sender didn't provide one, generate server-side (not idempotent but still stored)
		clientID = uuid.New()
	}

	var saved *model.Message
	if c.msgRepo != nil {
		msg := &model.Message{
			ClientID:    clientID,
			SenderID:    senderUUID,
			RecipientID: recipientUUID,
			Body:        dm.Content,
			State:       model.StatePending,
		}
		saved, err = c.msgRepo.Create(context.Background(), msg)
		if err != nil {
			logger.Log.Error().Err(err).Msg("failed to persist message")
			return
		}
		logger.Log.Info().
			Str("message_id", saved.ID.String()).
			Str("from", c.userID).
			Str("to", dm.To).
			Msg("message persisted")
	}

	outgoing, err := json.Marshal(Envelope{
		Type: "dm",
		Payload: mustMarshal(DirectMessage{
			ClientID: clientID.String(),
			To:       dm.To,
			Content:  dm.Content,
		}),
	})
	if err != nil {
		logger.Log.Error().Err(err).Msg("failed to marshal outgoing DM")
		return
	}

	recipient := c.hub.GetClient(dm.To)
	if recipient == nil {
		logger.Log.Debug().Str("to", dm.To).Msg("recipient offline, message saved for later delivery")
		return
	}

	select {
	case recipient.send <- outgoing:
		if c.msgRepo != nil && saved != nil {
			if updateErr := c.msgRepo.UpdateState(context.Background(), saved.ID, model.StateSent); updateErr != nil {
				logger.Log.Warn().Err(updateErr).Msg("failed to update message state to sent")
			}
		}
		logger.Log.Debug().Str("to", dm.To).Msg("message pushed to recipient send channel")
	default:
		logger.Log.Warn().Str("to", dm.To).Msg("slow client: send channel full, dropping real-time delivery")
	}
}

func (c *Client) writePump() {
	ticker := time.NewTicker(pingPeriod)
	defer func() {
		ticker.Stop()
		c.conn.Close()
		logger.Log.Debug().Str("userID", c.userID).Msg("writePump exited")
	}()

	for {
		select {
		case message, ok := <-c.send:
			c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if !ok {
				c.conn.WriteMessage(websocket.CloseMessage, []byte{})
				return
			}

			w, err := c.conn.NextWriter(websocket.TextMessage)
			if err != nil {
				return
			}
			w.Write(message)

			n := len(c.send)
			for i := 0; i < n; i++ {
				w.Write([]byte("\n"))
				w.Write(<-c.send)
			}

			if err := w.Close(); err != nil {
				return
			}
		case <-ticker.C:
			c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if err := c.conn.WriteMessage(websocket.PingMessage, nil); err != nil {
				return
			}
		}
	}
}

func mustMarshal(v interface{}) json.RawMessage {
	data, err := json.Marshal(v)
	if err != nil {
		panic("marshal failed: " + err.Error())
	}
	return data
}