package repository

import (
	"context"
	"fmt"

	"github.com/Rengoku1926/wp_proto/apps/backend/internal/model"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type MessageRepo struct {
	pool *pgxpool.Pool
}

func NewMessageRepo(pool *pgxpool.Pool) *MessageRepo {
	return &MessageRepo{pool: pool}
}

func (r *MessageRepo) Create(ctx context.Context, msg *model.Message) (*model.Message, error){
	// inserts a new message. 
	// if a message with the same client_id already exists then the existing message/row is returned. 
	// idempotency is achieved throught the client_id which is a uuid generated by the sender.
	query := `INSERT INTO messages (client_id, sender_id, recipient_id, group_id, body, state) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (client_id) DO NOTHING RETURNING id, client_id, sender_id, recipient_id, group_id, body, state, created_at, updated_at`

	row := r.pool.QueryRow(ctx, query,msg.ClientID, msg.SenderID, msg.RecipientID, msg.GroupID, msg.Body, msg.State)

	var out model.Message

	err := row.Scan(&out.ID, &out.ClientID, &out.SenderID, &out.RecipientID,
		&out.GroupID, &out.Body, &out.State, &out.CreatedAt, &out.UpdatedAt)

	if err == pgx.ErrNoRows {
		// conflict -- fetch the existing row instead
		return r.GetByClientID(ctx, msg.ClientID)
	}
	if err != nil{
		return nil, fmt.Errorf("message insert: %w", err)
	}
	return &out, nil
}

func (r *MessageRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Message, error){
	query := `SELECT id, client_id, sender_id, recipient_id, group_id, body, state, created_at, updated_at FROM messages WHERE id = $1`
	var m model.Message

	err := r.pool.QueryRow(ctx, query, id).Scan(&m.ID, &m.ClientID, &m.SenderID, &m.RecipientID,
		&m.GroupID, &m.Body, &m.State, &m.CreatedAt, &m.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("message get by id : %w", err)
	}
	return &m, nil
}

func (r *MessageRepo) GetByClientID(ctx context.Context, clientID uuid.UUID) (*model.Message, error){
	query := `SELECT id, client_id, sender_id, recipient_id, group_id, body, state, created_at, updated_at, updated_at FROM messages WHERE client_id = $1`

	var m  model.Message
	err := r.pool.QueryRow(ctx, query, clientID).Scan(&m.ID, &m.ClientID, &m.SenderID, &m.RecipientID, &m.GroupID, &m.Body, &m.State, &m.CreatedAt, &m.UpdatedAt)

	if err != nil{
		return nil, fmt.Errorf("message get by client_id: %w", err)
	}
	return &m, nil
}

func (r *MessageRepo) UpdateState(ctx context.Context, id uuid.UUID, state model.DeliveryState) error {
	query := `UPDATE messages SET state = $1, updated_at = now() WHERE id = $2`
	
	tag, err := r.pool.Exec(ctx, query, state, id)
	if err != nil {
		return fmt.Errorf("message update state : %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("message %s not found ", id)
	}
	return nil
}